# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  when you don't create things, you become defined by your tastes rather than ability. 
  your tastes only narrow & exclude people. so create.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tokhi.github.io/" # the base hostname & protocol for your site
twitter_username: s_tokhi
github_username:  tokhi

# Build settings
markdown: kramdown
